### ISSUE TITLE
Add examples to README

### ISSUE THREAD

**Issue by munierujp** [azu/mocha-migrate#2]
Could you add examples to README?

### Input
`mocha.opts`: 

```
--require ts-node/register
--reporter spec
--recursive
```

### Output
`.mocharc.json`:

```json
{
  "require": [
    "ts-node/register"
  ],
  "reporter": "spec",
  "recursive": true
}
```

`.mocharc.js`:

```js
(module.exports = {
    "require": ["ts-node/register"],
    "reporter": "spec",
    "recursive": true
})
```

`.mocharc.yml` or `.mocharc.yaml`:

```yaml
---
  require: 
    - "ts-node/register"
  reporter: "spec"
  recursive: true
```

For showing examples of several types, it's using...

- `require` (for array)
- `reporter` (for string)
- `recursive` (for boolean)

But there may be other better examples.
